First Pull Request!
Zelalem1222/Hello-Microverse pull request #1
Opened 2022-04-19 12:51 UTC by Zelalem1222

2022-04-19 13:11 UTC, prolajumokeoni requested changes
Hi @Zelalem1222,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used




## Required Changes ♻️

- [ ]  Kindly setup [GitHub actions ](https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-github-actions) by adding the  .github/workflows folder and add a copy of [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml), you can also  add [.stylelintrc.json](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json) and [.hintrc](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) to your root project so you can set up linters locally, also don't forget to add node_modules to .gitignore so you don't add it to git 🤝 

- [ ] Kindly add a  descriptive pull request message as this is part of the requirement, it should be a brief summary describing changes introduced in your pr.

_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 13:11 UTC, prolajumokeoni commented on README.md
> +   Html and css
- [ ] Kindly make your readme file more descriptive by using the [microverse readme template](https://github.com/microverseinc/readme-template) this make your project more descriptive and professional 👍🏿

2022-04-19 14:46 UTC, MeqdamAlqudah requested changes
Hi @Zelalem1222 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![](https://media4.giphy.com/media/3o6wNGz5IgfyeEXrnq/200.webp?cid=ecf05e479xqhcjirbp9ng8twaykc9kttavihrc7qydrjvf78&rid=200.webp&ct=g)
## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-19 14:46 UTC, MeqdamAlqudah commented on .github
> +
- [ ] Please your linters are not working as I noticed and as the last reviewer told you she described the problem " Kindly setup [GitHub actions ](https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-github-actions)by adding the .github/workflows folder and add a copy of [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml), you can also add [.stylelintrc.json](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json) and [.hintrc](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) to your root project so you can set up linters locally, also don't forget to add node_modules to .gitignore so you don't add it to git 🤝"

there should be 3 checks here for web hint ,silent and Lighthouse

2022-04-19 14:46 UTC, MeqdamAlqudah commented on .github
> +
- [Optional ] Please commit should be in the present tense 

![image](https://user-images.githubusercontent.com/74744787/164030940-3668aaf2-a562-49be-aab0-4ddcab2ae005.png)

2022-04-19 14:54 UTC, Zelalem1222 commented on .github
> +
I have already created .github folder and added a copy of [.github/workflows/linters.yml]. Is there anything I have to add?

2022-04-19 15:20 UTC, Zelalem1222 commented
Hi, @prolajumokeoni
 Can you please help me? I do not know what I am doing wrong.

2022-04-19 15:24 UTC, prolajumokeoni commented
> Hi, @prolajumokeoni Can you please help me? I do not know what I am doing wrong.

- [ ] Kindly add the right content to your [linters.yml ](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) file in your .github/workflows folder

2022-04-19 15:30 UTC, Zelalem1222 commented
@prolajumokeoni 
Is there any video or something that I can see? I am not understanding anything.

2022-04-19 16:02 UTC, prolajumokeoni commented
> @prolajumokeoni Is there any video or something that I can see? I am not understanding anything.

Microverse linters         |  Zelalem linter config  
:-------------------------:|:-------------------------:
![Screenshot_30](https://user-images.githubusercontent.com/69638013/164042745-c3a610d1-91ec-4c2c-978b-aa39dc09efb1.png)  |  ![Screenshot_29](https://user-images.githubusercontent.com/69638013/164042776-d9997144-7981-49a2-bfa7-3f3c3e57e68c.png)

Kindly check the previous comment in my [summary](https://github.com/Zelalem1222/Hello-Microverse/pull/1#pullrequestreview-945685700)

### What you need to do ⬇️ 
- Create a .github folder ➡️  Create a workflows folder in your  .github folder ➡️ then create a linters.yml file and add the content  your folder structure should look  like this [.github](https://github.com/microverseinc/linters-config/tree/master/html-css/.github)/[workflows](https://github.com/microverseinc/linters-config/tree/master/html-css/.github/workflows)

2022-04-19 17:16 UTC, Zelalem1222 commented
@prolajumokeoni Is it fixed now?

2022-04-19 17:33 UTC, prolajumokeoni commented
> @prolajumokeoni Is it fixed now?

No, it's not fixed yet

2022-04-19 19:36 UTC, Zelalem1222 commented
@prolajumokeoni is it working now? and can I create new pull request?

2022-04-20 07:57 UTC, danmainah approved these changes
Hi @Zelalem1222 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me using @danmainah in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 07:57 UTC, danmainah commented on styles.css
> +}
- [ ] [OPTIONAL] It's always good practice to use classes instead of HTML elements.

2022-04-20 08:06 UTC, merged